### ISSUE TITLE
pip install issue -- HISTORY.rst

### ISSUE THREAD

**Issue by hemskgren** [networklore/rasa#1]
Hello Patrick
## [root@ansible ansible-cisco-asa]# cat /root/.pip/pip.log

/bin/pip run on Tue Jun  2 09:02:27 2015
Downloading/unpacking rasa
  Getting page https://pypi.python.org/simple/rasa/
  URLs to search for versions for rasa:
- https://pypi.python.org/simple/rasa/
  Analyzing links from page https://pypi.python.org/simple/rasa/
    Found link https://pypi.python.org/packages/source/r/rasa/rasa-0.0.1.tar.gz#md5=6038ae767398d8e5e5d48711d866c293 (from https://pypi.python.org/simple/rasa/), version: 0.0.1
    Found link https://pypi.python.org/packages/source/r/rasa/rasa-0.0.2.tar.gz#md5=74c68d011ab03574258b0d071dd52513 (from https://pypi.python.org/simple/rasa/), version: 0.0.2
    Found link https://pypi.python.org/packages/source/r/rasa/rasa-0.0.3.tar.gz#md5=adc52545c942c8a1f5dcd33a53dc5382 (from https://pypi.python.org/simple/rasa/), version: 0.0.3
  Using version 0.0.3 (newest of versions: 0.0.3, 0.0.2, 0.0.1)
  Downloading rasa-0.0.3.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/r/rasa/rasa-0.0.3.tar.gz#md5=adc52545c942c8a1f5dcd33a53dc5382 (from https://pypi.python.org/simple/rasa/)
  Running setup.py (path:/tmp/pip-build-SB_gVb/rasa/setup.py) egg_info for package rasa
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-SB_gVb/rasa/setup.py", line 14, in <module>
        with open('HISTORY.rst', 'r', 'utf-8') as f:
      File "/usr/lib64/python2.7/codecs.py", line 881, in open
        file = **builtin**.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: 'HISTORY.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  
  File "<string>", line 17, in <module>
  
  File "/tmp/pip-build-SB_gVb/rasa/setup.py", line 14, in <module>
  
    with open('HISTORY.rst', 'r', 'utf-8') as f:
  
  File "/usr/lib64/python2.7/codecs.py", line 881, in open
  
    file = **builtin**.open(filename, mode, buffering)

IOError: [Errno 2] No such file or directory: 'HISTORY.rst'

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-SB_gVb/rasa
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 298, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 1234, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/site-packages/pip/util.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-SB_gVb/rasa
[root@ansible ansible-cisco-asa]#

Regards
Christer

**Comment by ogenstad** [comment]
Thanks, the HISTORY.rst file wasn't included in the distribution. I've added this in rasa 0.0.4. Please try to install again. Perhaps using:
pip install rasa --no-cache-dir

Let me know if it works for you now.

**Comment by hemskgren** [comment]
Thanks it works.

Christer

**Comment by ogenstad** [comment]
Ok, thanks for letting me know!

Patrick

**Comment by vibhor-mungee** [comment]
Getting this issue again-

pip3 --version - 21.0.1
python3 --version -  3.9.1

pip3 install --upgrade rasa
Requirement already satisfied: rasa in ./venv/lib/python3.9/site-packages (0.0.5)
Collecting rasa
  Using cached rasa-1.10.2-py3-none-any.whl (510 kB)
Collecting cloudpickle<1.4,>=1.2
  Downloading cloudpickle-1.3.0-py2.py3-none-any.whl (26 kB)
Collecting colorhash<1.1.0,>=1.0.2
  Using cached colorhash-1.0.3-py3-none-any.whl (4.0 kB)
Collecting python-engineio<3.13,>=3.11
  Downloading python_engineio-3.12.1-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 1.2 MB/s

Collecting psycopg2-binary<2.9.0,>=2.8.2
  Using cached psycopg2_binary-2.8.6-cp39-cp39-macosx_10_9_x86_64.macosx_10_9_intel.macosx_10_10_intel.macosx_10_10_x86_64.whl (1.5 MB)
Collecting ruamel.yaml<0.17,>=0.16
  Using cached ruamel.yaml-0.16.12-py2.py3-none-any.whl (111 kB)
Collecting prompt-toolkit<3.0,>=2.0
  Using cached prompt_toolkit-2.0.10-py3-none-any.whl (340 kB)
Collecting python-dateutil<2.9,>=2.8
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting gevent<1.6,>=1.4
  Using cached gevent-1.5.0.tar.gz (5.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting tensorflow-estimator==2.1.0
  Using cached tensorflow_estimator-2.1.0-py2.py3-none-any.whl (448 kB)
Collecting PyJWT<1.8,>=1.7
  Using cached PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
Collecting absl-py<0.10,>=0.9
  Using cached absl-py-0.9.0.tar.gz (104 kB)
Requirement already satisfied: setuptools>=41.0.0 in ./venv/lib/python3.9/site-packages (from rasa) (52.0.0)
Collecting multidict<5.0,>=4.6
  Using cached multidict-4.7.6.tar.gz (50 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting rasa-sdk<2.0.0,>=1.10.0
  Using cached rasa_sdk-1.10.3-py3-none-any.whl (39 kB)
Collecting jsonpickle<1.5,>=1.3
  Using cached jsonpickle-1.4.2-py2.py3-none-any.whl (36 kB)
Requirement already satisfied: requests<3.0,>=2.23 in ./venv/lib/python3.9/site-packages (from rasa) (2.25.1)
Collecting packaging<21.0,>=20.0
  Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 9.7 MB/s
Collecting numpy<2.0,>=1.16
  Using cached numpy-1.20.1-cp39-cp39-macosx_10_9_x86_64.whl (16.1 MB)
Collecting python-telegram-bot<13.0,>=11.1
  Downloading python_telegram_bot-12.8-py2.py3-none-any.whl (375 kB)
     |████████████████████████████████| 375 kB 487 kB/s
Collecting rasa
  Using cached rasa-1.10.1-py3-none-any.whl (509 kB)
  Using cached rasa-1.10.0-py3-none-any.whl (509 kB)
  Using cached rasa-1.9.7-py3-none-any.whl (497 kB)
Collecting tensorflow-probability<0.8,>=0.7
  Using cached tensorflow_probability-0.7.0-py2.py3-none-any.whl (981 kB)
Collecting gevent<1.5.0,>=1.4.0
  Downloading gevent-1.4.0.tar.gz (5.2 MB)
     |████████████████████████████████| 5.2 MB 723 kB/s
Collecting sanic-jwt<1.4.0,>=1.3.2
  Using cached sanic-jwt-1.3.2.tar.gz (18 kB)
Collecting python-socketio<4.5,>=4.4
  Using cached python_socketio-4.4.0-py2.py3-none-any.whl (50 kB)
Collecting jsonpickle<1.4,>=1.3
  Using cached jsonpickle-1.3-py2.py3-none-any.whl (32 kB)
Collecting tensorflow_hub<0.8,>=0.7
  Using cached tensorflow_hub-0.7.0-py2.py3-none-any.whl (89 kB)
Collecting ujson<2.0,>=1.35
  Using cached ujson-1.35.tar.gz (192 kB)
Collecting apscheduler<3.7,>=3.6
  Downloading APScheduler-3.6.3-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 771 kB/s
Collecting cloudpickle<1.3.0,>=1.2.0
  Using cached cloudpickle-1.2.2-py2.py3-none-any.whl (25 kB)
Collecting sklearn-crfsuite<0.4,>=0.3
  Using cached sklearn_crfsuite-0.3.6-py2.py3-none-any.whl (12 kB)
Collecting pytz<2020.0,>=2019.1
  Using cached pytz-2019.3-py2.py3-none-any.whl (509 kB)
Collecting twilio<6.27,>=6.26
  Using cached twilio-6.26.3-py2.py3-none-any.whl (979 kB)
Collecting rocketchat_API<0.7.0,>=0.6.31
  Using cached rocketchat_API-0.6.36-py3-none-any.whl (9.5 kB)
Collecting scipy<2.0.0,>=1.4.1
  Using cached scipy-1.6.0-cp39-cp39-macosx_10_9_x86_64.whl (30.9 MB)
Collecting pika<1.2.0,>=1.1.0
  Downloading pika-1.1.0-py2.py3-none-any.whl (148 kB)
     |████████████████████████████████| 148 kB 1.1 MB/s
Collecting fbmessenger<6.1.0,>=6.0.0
  Using cached fbmessenger-6.0.0-py2.py3-none-any.whl (11 kB)
Collecting kafka-python<2.0,>=1.4
  Using cached kafka_python-1.4.7-py2.py3-none-any.whl (266 kB)
Collecting jsonschema<3.3,>=3.2
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting rasa
  Using cached rasa-1.9.6-py3-none-any.whl (497 kB)
  Using cached rasa-1.9.5-py3-none-any.whl (496 kB)
  Using cached rasa-1.9.4-py3-none-any.whl (495 kB)
  Using cached rasa-1.9.3-py3-none-any.whl (495 kB)
  Using cached rasa-1.9.2-py3-none-any.whl (495 kB)
  Using cached rasa-1.9.1-py3-none-any.whl (495 kB)
  Using cached rasa-1.9.0-py3-none-any.whl (495 kB)
  Using cached rasa-1.8.3-py3-none-any.whl (483 kB)
  Using cached rasa-1.8.2-py3-none-any.whl (483 kB)
  Using cached rasa-1.8.1-py3-none-any.whl (481 kB)
  Using cached rasa-1.8.0-py3-none-any.whl (481 kB)
  Using cached rasa-1.7.4-py3-none-any.whl (575 kB)
Collecting boto3~=1.9
  Using cached boto3-1.17.9.tar.gz (100 kB)
Collecting pika~=1.0.0
  Using cached pika-1.0.1-py2.py3-none-any.whl (148 kB)
Collecting pydot~=1.4
  Using cached pydot-1.4.2-py2.py3-none-any.whl (21 kB)
Collecting questionary>=1.1.0
  Using cached questionary-1.9.0-py3-none-any.whl (32 kB)
Collecting matplotlib~=3.0
  Using cached matplotlib-3.3.4-cp39-cp39-macosx_10_9_x86_64.whl (8.5 MB)
Collecting absl-py>=0.8.0
  Using cached absl_py-0.11.0-py3-none-any.whl (127 kB)
Collecting gym<=0.15.4
  Using cached gym-0.15.4.tar.gz (1.6 MB)
Collecting coloredlogs~=10.0
  Using cached coloredlogs-10.0-py2.py3-none-any.whl (47 kB)
Collecting redis~=3.3.5
  Using cached redis-3.3.11-py2.py3-none-any.whl (66 kB)
Collecting attrs>=18
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting sanic-cors==0.9.9.post1
  Using cached Sanic_Cors-0.9.9.post1-py2.py3-none-any.whl (16 kB)
Collecting aiohttp~=3.5
  Using cached aiohttp-3.7.3-cp39-cp39-macosx_10_14_x86_64.whl (648 kB)
Collecting sanic-jwt~=1.3
  Using cached sanic-jwt-1.6.0.tar.gz (19 kB)
Collecting jsonpickle~=1.1
  Using cached jsonpickle-1.5.2-py2.py3-none-any.whl (37 kB)
Collecting multidict==4.6.1
  Using cached multidict-4.6.1.tar.gz (115 kB)
Collecting sanic~=19.9.0
  Using cached sanic-19.9.0-py3-none-any.whl (73 kB)
Collecting tensor2tensor~=1.14.0
  Using cached tensor2tensor-1.14.1-py2.py3-none-any.whl (1.6 MB)
Collecting packaging~=19.0
  Using cached packaging-19.2-py2.py3-none-any.whl (30 kB)
Collecting apscheduler~=3.0
  Using cached APScheduler-3.7.0-py2.py3-none-any.whl (59 kB)
Collecting ruamel.yaml~=0.15.0
  Using cached ruamel.yaml-0.15.100.tar.gz (318 kB)
Collecting twilio~=6.0
  Using cached twilio-6.52.0.tar.gz (460 kB)
Collecting rasa
  Using cached rasa-1.7.3-py3-none-any.whl (575 kB)
  Using cached rasa-1.7.2-py3-none-any.whl (575 kB)
  Using cached rasa-1.7.1-py3-none-any.whl (574 kB)
  Using cached rasa-1.7.0-py3-none-any.whl (573 kB)
  Using cached rasa-1.6.2-py3-none-any.whl (559 kB)
Collecting rasa-sdk~=1.6.0
  Using cached rasa_sdk-1.6.1-py2.py3-none-any.whl (32 kB)
Collecting rasa
  Using cached rasa-1.6.1-py3-none-any.whl (559 kB)
  Using cached rasa-1.6.0-py3-none-any.whl (558 kB)
  Using cached rasa-1.5.3-py3-none-any.whl (530 kB)
Collecting rasa-sdk~=1.5.0
  Using cached rasa_sdk-1.5.2-py2.py3-none-any.whl (32 kB)
Collecting rasa
  Using cached rasa-1.5.2-py3-none-any.whl (529 kB)
  Using cached rasa-1.5.1-py3-none-any.whl (529 kB)
  Using cached rasa-1.5.0-py3-none-any.whl (527 kB)
  Using cached rasa-1.4.6-py3-none-any.whl (518 kB)
  Using cached rasa-1.4.5-py3-none-any.whl (517 kB)
  Using cached rasa-1.4.4-py3-none-any.whl (517 kB)
  Using cached rasa-1.4.3-py3-none-any.whl (518 kB)
Collecting SQLAlchemy~=1.3.0
  Using cached SQLAlchemy-1.3.23-cp39-cp39-macosx_10_14_x86_64.whl (1.2 MB)
Collecting gast==0.2.2
  Using cached gast-0.2.2.tar.gz (10 kB)
Collecting python-engineio>=3.9.3
  Using cached python_engineio-4.0.0-py2.py3-none-any.whl (50 kB)
Collecting slackclient~=1.3
  Using cached slackclient-1.3.2.tar.gz (16 kB)
Collecting tqdm~=4.0
  Using cached tqdm-4.56.2-py2.py3-none-any.whl (72 kB)
Collecting terminaltables~=3.1
  Using cached terminaltables-3.1.0.tar.gz (12 kB)
Collecting webexteamssdk~=1.1
  Using cached webexteamssdk-1.6-py3-none-any.whl (113 kB)
Collecting mattermostwrapper~=2.0
  Using cached mattermostwrapper-2.2.tar.gz (2.5 kB)
Collecting rasa
  Using cached rasa-1.4.2-py3-none-any.whl (516 kB)
  Using cached rasa-1.4.1-py3-none-any.whl (516 kB)
  Using cached rasa-1.4.0-py3-none-any.whl (515 kB)
  Using cached rasa-1.3.10-py3-none-any.whl (507 kB)
Collecting sanic-cors~=0.9.0
  Using cached Sanic_Cors-0.9.9.post4-py2.py3-none-any.whl (16 kB)
Collecting simplejson~=3.16
  Using cached simplejson-3.17.2.tar.gz (83 kB)
Collecting rasa
  Using cached rasa-1.3.9-py3-none-any.whl (506 kB)
  Using cached rasa-1.3.8-py3-none-any.whl (505 kB)
  Using cached rasa-1.3.7-py3-none-any.whl (505 kB)
  Using cached rasa-1.3.6-py3-none-any.whl (505 kB)
Collecting pymongo~=3.8
  Using cached pymongo-3.11.3-cp39-cp39-macosx_10_9_x86_64.whl (380 kB)
Collecting rasa
  Using cached rasa-1.3.4-py3-none-any.whl (504 kB)
  Using cached rasa-1.3.3-py3-none-any.whl (503 kB)
  Using cached rasa-1.3.2-py3-none-any.whl (502 kB)
  Using cached rasa-1.3.1-py3-none-any.whl (502 kB)
  Using cached rasa-1.3.0-py3-none-any.whl (502 kB)
  Using cached rasa-1.2.12-py3-none-any.whl (471 kB)
Collecting fakeredis~=1.0
  Using cached fakeredis-1.4.5-py3-none-any.whl (35 kB)
Collecting python-socketio~=4.0
  Using cached python_socketio-4.6.1-py2.py3-none-any.whl (51 kB)
Collecting rasa
  Using cached rasa-1.2.11-py3-none-any.whl (471 kB)
  Using cached rasa-1.2.10-py3-none-any.whl (471 kB)
  Using cached rasa-1.2.9-py3-none-any.whl (471 kB)
  Using cached rasa-1.2.8-py3-none-any.whl (471 kB)
  Using cached rasa-1.2.7-py3-none-any.whl (471 kB)
  Using cached rasa-1.2.6-py3-none-any.whl (470 kB)
  Using cached rasa-1.2.5-py3-none-any.whl (470 kB)
  Using cached rasa-1.2.4-py3-none-any.whl (469 kB)
  Using cached rasa-1.2.3-py3-none-any.whl (469 kB)
Collecting rasa-sdk~=1.1.0
  Downloading rasa_sdk-1.1.1-py2.py3-none-any.whl (22 kB)
Collecting rasa
  Using cached rasa-1.2.2-py3-none-any.whl (468 kB)
  Using cached rasa-1.2.1-py3-none-any.whl (468 kB)
  Using cached rasa-1.2.0-py3-none-any.whl (468 kB)
  Using cached rasa-1.1.8-py3-none-any.whl (464 kB)
  Using cached rasa-1.1.7-py3-none-any.whl (455 kB)
  Using cached rasa-1.1.6-py3-none-any.whl (453 kB)
  Using cached rasa-1.1.5-py3-none-any.whl (452 kB)
  Using cached rasa-1.1.4-py3-none-any.whl (447 kB)
  Using cached rasa-1.1.3-py3-none-any.whl (446 kB)
  Using cached rasa-1.1.2-py3-none-any.whl (444 kB)
  Using cached rasa-1.1.1-py3-none-any.whl (444 kB)
  Using cached rasa-1.1.0-py3-none-any.whl (444 kB)
Collecting rasa-sdk~=1.0.0rc4
  Using cached rasa_sdk-1.0.0-py2.py3-none-any.whl (22 kB)
Collecting rasa
  Using cached rasa-1.0.9-py3-none-any.whl (440 kB)
  Using cached rasa-1.0.8-py3-none-any.whl (440 kB)
  Using cached rasa-1.0.7-py3-none-any.whl (439 kB)
  Using cached rasa-1.0.6-py3-none-any.whl (438 kB)
  Using cached rasa-1.0.5-py3-none-any.whl (438 kB)
  Using cached rasa-1.0.4-py3-none-any.whl (438 kB)
  Using cached rasa-1.0.3-py3-none-any.whl (438 kB)
  Using cached rasa-1.0.2-py3-none-any.whl (438 kB)
  Using cached rasa-1.0.1-py3-none-any.whl (436 kB)
  Using cached rasa-1.0.0-py3-none-any.whl (436 kB)
  Using cached rasa-0.1.1-py3-none-any.whl (6.1 kB)
Collecting rasa-core
  Using cached rasa_core-0.14.5-py3-none-any.whl (212 kB)
Collecting rasa-nlu
  Using cached rasa_nlu-0.15.1-py3-none-any.whl (147 kB)
Collecting packaging~=18.0
  Using cached packaging-18.0-py2.py3-none-any.whl (21 kB)
Collecting pytz~=2018.9
  Using cached pytz-2018.9-py2.py3-none-any.whl (510 kB)
Collecting python-socketio~=3.0
  Using cached python_socketio-3.1.2-py2.py3-none-any.whl (43 kB)
Collecting fbmessenger~=5.0
  Using cached fbmessenger-5.6.0-py2.py3-none-any.whl (11 kB)
Collecting redis~=2.0
  Using cached redis-2.10.6-py2.py3-none-any.whl (64 kB)
Collecting pika~=0.12.0
  Using cached pika-0.12.0-py2.py3-none-any.whl (108 kB)
Collecting fakeredis~=0.10.0
  Using cached fakeredis-0.10.3-py2.py3-none-any.whl (27 kB)
Collecting flask-jwt-simple~=0.0.3
  Using cached Flask-JWT-Simple-0.0.3.tar.gz (6.9 kB)
Collecting rasa-core
  Using cached rasa_core-0.14.4-py3-none-any.whl (212 kB)
  Using cached rasa_core-0.14.3-py3-none-any.whl (212 kB)
  Using cached rasa_core-0.14.2-py3-none-any.whl (212 kB)
  Using cached rasa_core-0.14.1-py3-none-any.whl (212 kB)
Collecting rasa-nlu
  Using cached rasa_nlu-0.15.0-py3-none-any.whl (147 kB)
Collecting rasa-core-sdk~=0.13.1
  Using cached rasa_core_sdk-0.13.1-py2.py3-none-any.whl (20 kB)
Collecting rasa-core
  Using cached rasa_core-0.14.0-py3-none-any.whl (212 kB)
  Using cached rasa_core-0.13.8-py3-none-any.whl (205 kB)
Collecting rasa-nlu
  Using cached rasa_nlu-0.14.6-py2.py3-none-any.whl (147 kB)
Collecting rasa-core
  Using cached rasa_core-0.13.7-py3-none-any.whl (205 kB)
  Using cached rasa_core-0.13.6-py3-none-any.whl (205 kB)
  Using cached rasa_core-0.13.5-py3-none-any.whl (204 kB)
  Using cached rasa_core-0.13.4-py3-none-any.whl (204 kB)
  Using cached rasa_core-0.13.3-py3-none-any.whl (204 kB)
  Using cached rasa_core-0.13.2-py3-none-any.whl (204 kB)
  Using cached rasa_core-0.13.1-py3-none-any.whl (204 kB)
  Using cached rasa_core-0.13.0-py3-none-any.whl (204 kB)
  Using cached rasa_core-0.12.4-py2.py3-none-any.whl (204 kB)
Collecting pyyaml~=3.12
  Using cached PyYAML-3.13.tar.gz (270 kB)
Collecting ConfigArgParse~=0.13.0
  Using cached ConfigArgParse-0.13.0.tar.gz (31 kB)
Collecting python-socketio~=2.0
  Using cached python_socketio-2.1.2-py2.py3-none-any.whl (33 kB)
Collecting rasa-core
  Using cached rasa_core-0.12.3-py2.py3-none-any.whl (204 kB)
  Using cached rasa_core-0.12.2-py2.py3-none-any.whl (203 kB)
  Using cached rasa_core-0.12.1-py2.py3-none-any.whl (203 kB)
  Using cached rasa_core-0.12.0-py2.py3-none-any.whl (201 kB)
  Using cached rasa_core-0.11.12-py2.py3-none-any.whl (179 kB)
  Using cached rasa_core-0.11.11-py2.py3-none-any.whl (179 kB)
  Using cached rasa_core-0.11.10-py2.py3-none-any.whl (179 kB)
  Using cached rasa_core-0.11.9-py2.py3-none-any.whl (179 kB)
  Using cached rasa_core-0.11.8-py2.py3-none-any.whl (179 kB)
Collecting PyInquirer~=1.0
  Using cached PyInquirer-1.0.3.tar.gz (27 kB)
Collecting rasa-core-sdk~=0.11.0
  Using cached rasa_core_sdk-0.11.5-py2.py3-none-any.whl (14 kB)
Collecting keras~=2.0
  Using cached Keras-2.4.3-py2.py3-none-any.whl (36 kB)
Collecting rasa-core
  Using cached rasa_core-0.11.7-py2.py3-none-any.whl (178 kB)
  Using cached rasa_core-0.11.6-py2.py3-none-any.whl (178 kB)
  Using cached rasa_core-0.11.5-py2.py3-none-any.whl (178 kB)
  Using cached rasa_core-0.11.4-py2.py3-none-any.whl (178 kB)
  Using cached rasa_core-0.11.3-py2.py3-none-any.whl (168 kB)
  Using cached rasa_core-0.11.2-py2.py3-none-any.whl (166 kB)
  Using cached rasa_core-0.11.1-py2.py3-none-any.whl (166 kB)
  Using cached rasa_core-0.11.0-py2.py3-none-any.whl (166 kB)
  Using cached rasa_core-0.10.4-py2.py3-none-any.whl (133 kB)
Collecting flask~=1.0
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting six~=1.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting jsonpickle~=0.9.0
  Using cached jsonpickle-0.9.6.tar.gz (67 kB)
Collecting h5py~=2.0
  Using cached h5py-2.10.0.tar.gz (301 kB)
Collecting graphviz~=0.8.0
  Using cached graphviz-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting flask-cors~=3.0
  Using cached Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Collecting rasa-nlu
  Using cached rasa_nlu-0.13.8-py2.py3-none-any.whl (145 kB)
Collecting rasa-core
  Using cached rasa_core-0.10.3-py2.py3-none-any.whl (133 kB)
  Using cached rasa_core-0.10.2-py2.py3-none-any.whl (133 kB)
Collecting rasa-nlu
  Using cached rasa_nlu-0.12.3-py2.py3-none-any.whl (131 kB)
Collecting rasa-core
  Using cached rasa_core-0.10.1-py2.py3-none-any.whl (132 kB)
  Using cached rasa_core-0.10.0-py2.py3-none-any.whl (132 kB)
  Using cached rasa_core-0.9.8-py2.py3-none-any.whl (125 kB)
  Using cached rasa_core-0.9.7-py2.py3-none-any.whl (125 kB)
  Using cached rasa_core-0.9.6-py2.py3-none-any.whl (125 kB)
  Using cached rasa_core-0.9.5-py2.py3-none-any.whl (125 kB)
  Using cached rasa_core-0.9.4-py2.py3-none-any.whl (125 kB)
  Using cached rasa_core-0.9.3-py2.py3-none-any.whl (121 kB)
  Using cached rasa_core-0.9.2-py2.py3-none-any.whl (121 kB)
  Using cached rasa_core-0.9.1-py2.py3-none-any.whl (121 kB)
  Using cached rasa_core-0.9.0-py2.py3-none-any.whl (121 kB)
  Using cached rasa_core-0.8.6-py2.py3-none-any.whl (103 kB)
Collecting slackclient
  Using cached slackclient-2.9.3-py2.py3-none-any.whl (96 kB)
Collecting fbmessenger<5.0.0
  Using cached fbmessenger-4.3.1-py2.py3-none-any.whl (10 kB)
Collecting graphviz
  Using cached graphviz-0.16-py2.py3-none-any.whl (19 kB)
Collecting rasa-nlu
  Using cached rasa_nlu-0.11.5.tar.gz (55 kB)
Collecting networkx
  Using cached networkx-2.5-py3-none-any.whl (1.6 MB)
Collecting jsonpickle
  Using cached jsonpickle-2.0.0-py2.py3-none-any.whl (37 kB)
Collecting redis
  Using cached redis-3.5.3-py2.py3-none-any.whl (72 kB)
Collecting nbsphinx
  Using cached nbsphinx-0.8.1-py3-none-any.whl (24 kB)
Collecting future
  Using cached future-0.18.2.tar.gz (829 kB)
Collecting rasa-core
  Using cached rasa_core-0.8.5.tar.gz (76 kB)
Collecting pandoc
  Using cached pandoc-1.0.2.tar.gz (488 kB)
Collecting typing>=3.6
  Using cached typing-3.7.4.3.tar.gz (78 kB)
Collecting rasa-core
  Using cached rasa_core-0.8.4.tar.gz (76 kB)
  Using cached rasa_core-0.8.3.tar.gz (76 kB)
  Using cached rasa_core-0.8.2.tar.gz (76 kB)
  Using cached rasa_core-0.8.1.tar.gz (75 kB)
  Using cached rasa_core-0.8.0.tar.gz (75 kB)
  Using cached rasa_core-0.7.9.tar.gz (61 kB)
  Using cached rasa_core-0.7.7.tar.gz (61 kB)
  Using cached rasa_core-0.7.6.tar.gz (60 kB)
  Using cached rasa_core-0.7.5.tar.gz (60 kB)
  Using cached rasa_core-0.7.4.tar.gz (60 kB)
  Using cached rasa_core-0.7.3.tar.gz (59 kB)
  Using cached rasa_core-0.7.2.tar.gz (59 kB)
  Using cached rasa_core-0.7.1.tar.gz (60 kB)
  Using cached rasa_core-0.7.0.tar.gz (60 kB)
INFO: pip is looking at multiple versions of rasa to determine which version is compatible with other requirements. This could take a while.
Collecting rasa
  Using cached rasa-0.1.0-py3-none-any.whl (6.1 kB)
  Using cached rasa-0.0.5-py3-none-any.whl
  Using cached rasa-0.0.4.tar.gz (5.0 kB)
  Using cached rasa-0.0.3.tar.gz (4.7 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/vibhormungee/Dev/rasa_chat_bot/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/s2/rv9nhs_92pl2qtq1j3z9w6840000gn/T/pip-install-lvailfm6/rasa_e4f9a37ce6d74e72bef1747f6d33631c/setup.py'"'"'; __file__='"'"'/private/var/folders/s2/rv9nhs_92pl2qtq1j3z9w6840000gn/T/pip-install-lvailfm6/rasa_e4f9a37ce6d74e72bef1747f6d33631c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/s2/rv9nhs_92pl2qtq1j3z9w6840000gn/T/pip-pip-egg-info-kwlpckg3
         cwd: /private/var/folders/s2/rv9nhs_92pl2qtq1j3z9w6840000gn/T/pip-install-lvailfm6/rasa_e4f9a37ce6d74e72bef1747f6d33631c/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/s2/rv9nhs_92pl2qtq1j3z9w6840000gn/T/pip-install-lvailfm6/rasa_e4f9a37ce6d74e72bef1747f6d33631c/setup.py", line 14, in <module>
        with open('HISTORY.rst', 'r', 'utf-8') as f:
      File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/77/56/5d44415d54043fb441b910bf86fa36bbb3b5565a507ba4ea933117cf109f/rasa-0.0.3.tar.gz#sha256=409e502bc20a29db848b68766decacad15a9cbeb68d1afd90add9945945c9048 (from https://pypi.org/simple/rasa/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached rasa-0.0.2.tar.gz (3.9 kB)
  Using cached rasa-0.0.1.tar.gz (1.6 kB)
Requirement already satisfied: idna<3,>=2.5 in ./venv/lib/python3.9/site-packages (from requests<3.0,>=2.23->rasa) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in ./venv/lib/python3.9/site-packages (from requests<3.0,>=2.23->rasa) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.9/site-packages (from requests<3.0,>=2.23->rasa) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.9/site-packages (from requests<3.0,>=2.23->rasa) (1.26.3)

**Comment by jaskirat-singh-pahwa** [comment]
Still getting the same error with rasa 0.0.5

**Comment by ogenstad** [comment]
As per the readme file this repo has been abandoned some years ago.
